export { getCardCombat, getCardValerio } from "./game/cards/CardAccessors.js";
export { getAttackPool, getDefensePool, getDraftCost, getDraftCostFromCombat } from "./game/cards/CardCombat.js";
export { getAbilityEffects, normalizeAbility, normalizeCard, normalizeCards } from "./game/cards/CardNormalizer.js";
export { makeDeck, shuffle } from "./game/cards/DeckFactory.js";
export { SETTINGS } from "./game/rules/ClassicSettings.js";
export { VALERIO_KEYS, VALERIO_LABELS } from "./game/valerio/Valerio.js";
export { getValerioTotal, validateCardValerio } from "./game/valerio/CardValerioValidation.js";
export { getNormalDamageCap, validateValerioDistribution, validateValerioPlan } from "./game/valerio/ValerioPlanValidation.js";
export { calculateAttackLine, calculateBreach } from "./game/systems/fight/FightDamage.js";
export { resolveActiveEffect, resolveTraitEffect } from "./game/systems/fight/FightEffects.js";
export { scoreFightPlan } from "./game/systems/fight/ClassicFightScoring.js";
